application/pdf: zathura
text/html: $BROWSER
text/xml: $TERM -e $EDITOR
application/xhtml_xml: $BROWSER
x-scheme-handler/http: $BROWSER
x-scheme-handler/https: $BROWSER
x-scheme-handler/ftp: $BROWSER
x-scheme-handler/about: $BROWSER
x-scheme-handler/unknown: $BROWSER

