#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)

# auth
exec-once = systemctl --user start hyprpolkitagent &
# automount
exec-once = udiskie &
# sync
exec-once = syncthing --no-browser &
# blue light filter
exec-once = wlsunset -t 2000 -T 6500 -l 49.2 -L 16.67 &
# taskbar
exec-once = waybar &
# wallpaper
exec-once = awww-daemon && bash -c 'awww img "$(cat ~/.cache/wal/wal)"'
# windows
exec-once = [workspace code]ghostty -e $scriptfolder/zellij-hook
