#!/usr/bin/env bash

current=$(bartib current | sed "/Warning:/d")
running=$(wc -l <<< "$current" )

if [[ $1 ]]; then
  if [[ $running -gt 1 ]]; then
    msg=$(bartib stop | tail -n 1)
  else
    msg=$(bartib continue | tail -n 1)
  fi

  notify-send "$(sed 's/).*//' <<< "$msg"))"
  pkill -RTMIN+6 waybar
else
  # Output JSON for Waybar
  alt=$([[ $running -gt 1 ]] && echo true || echo false)
  tooltip=$([[ $running -gt 1 ]] && echo "An activity is currently running." || echo "Start activity")
  jq -cn --arg alt "$alt" --arg tooltip "$tooltip" \
    '{alt:$alt, tooltip:$tooltip}'
fi
