#!/usr/bin/env bash
PATH="$PATH:$HOME/Projects/bartib/target/release"

if [[ $1 ]]; then
  msg=$(bartib toggle --nowarn)
  notify-send "$msg"
  pkill -RTMIN+6 waybar
  exit 0
fi

GOAL=150

proj=$(bartib current --nowarn --json | jq -r '.[0]["project"]')
bartib status --nowarn --project "$proj" --json | sed 's/<1m/0m/g' |
jq -rc --argjson goal "$GOAL" '
  def minutes:
    (
      (.today
       | match("(?:(\\d+)h)?\\s*(?:(\\d+)m)?")
       | .captures
       | map(.string // "0")
       | map(tonumber)
       | .[0] * 60 + .[1])
    );

  def clamp(min; max):
    if . < min then min
    elif . > max then max
    else .
    end;

  def bar(width):
    (minutes | clamp(0; $goal)) as $m
    | (($m * width) / $goal | floor) as $filled
    | if $filled >= 2
      then "\uE0B6" + ("\u2588" * ($filled - 2)) + "\uE0B4"
      else ""
      end;

  .activity as $a
  | ($a != null) as $active
  | (
      if $active
      then "Current activity: <b>\($a.description)</b> <i>(\($a.project))</i>"
      else ""
      end
    ) as $desc
  | ($desc | gsub("<[^>]*>"; "") | length) as $maxlen
  | (
      if $active
      then "\($desc)\nToday: <b>\(.today)</b>\n\n\((bar($maxlen)))"
      else "Start activity"
      end
    ) as $tooltip
  | {
      alt: $active,
      tooltip: $tooltip
    }
'
