#!/usr/bin/env bash

context=$(task _get rc.context)
if [[ ! -z $context ]]; then
  proj="<b>Project: $context</b>"
  proj+=$'\n'
  tasks=$(task simple start.any: rc.verbose: | head -n 5 | awk '{print " " $0}')
  tooltip="$proj$tasks"
else
  tooltip=$(task simple2 rc.verbose: | head -n 5 | awk '{printf " "; for (i=2; i<=NF; i++) printf "%s ", $i; print "<i>(" $1 "</i>) "}')
fi
count=$(task status:pending start.any: rc.verbose: count)

icon=
if [[ ! $count -eq 0 ]]; then
  # icon="${count}󱃔"
  icon="󱃔"
fi
# print json for waybar
jq -cn --arg text "$icon" --arg tooltip "$tooltip" \
  '{text:$text, tooltip:$tooltip}'
