[[mgr.prepend_keymap]]
on   = [ "g", "/" ]
run  = "cd /"
desc = "Cd to root"

[[mgr.prepend_keymap]]
on   = [ "g", "m" ]
run  = "cd /run/media/$USER"
desc = "Cd to mounted media"

[[mgr.prepend_keymap]]
on   = [ "g", "c" ]
run = ["hidden show", "cd ~/config"]
desc = "Cd to config"

[[mgr.prepend_keymap]]
on   = [ "g", "w" ]
run  = "cd ~/wallpapers"
desc = "Cd to wallpapers"
