#!/usr/bin/env bash

running=$(pgrep -x wlsunset)
echo "$running"
if [[ $running ]]; then
  pkill -x wlsunset
  [[ $1 != '-s' ]] && notify-send "Disabled night light"
else
  [[ $1 != '-s' ]] && notify-send "Enabled night light"
  systemd-run --user --quiet --no-block \
    wlsunset -t 2000 -T 6500 -l 49.2 -L 16.67
fi

