#!/usr/bin/bash

trap "notify-send 'Session finished.'; exit" SIGINT
notify-send 'Started pomodoro timer.'
while true; do
  sleep 25m
  notify-send 'Break time!'
  sleep 5m
  notify-send 'Time to work.'
done
