#!/usr/bin/env bash
source "$HOME/.zprofile"
tmp="$(mktemp -t wal-pick.XXXXXXX)"

$TERM --class="custom.float" -e yazi "$WALLPAPER_DIR" --chooser-file "$tmp"

selected="$(cat $tmp)"

if [ ! -z $selected ]; then
  if [[ -d $selected ]]; then
  notify-send "Selected random wallpaper from $selected."
  else
  notify-send "Selected $selected."
  fi
  echo $SCRIPT_DIR
wal -i "$selected" -o $SCRIPT_DIR/wallpaper-reload
else
notify-send "No wallpaper has been selected."
fi
