#!/usr/bin/env bash
# [[ -e $HOME/.config/qutebrowser/greasemonkey/ddg-bg.js ]] || (ln -s $HOME/.cache/wal/ddg-bg.js $HOME/.config/qutebrowser/greasemonkey/ && notify-send "Symlinked qutebrowser script.")
WALLPAPER="$(cat $HOME/.cache/wal/wal)"

makoctl reload

awww img "$WALLPAPER" --transition-type wipe --transition-angle 30
pkill -SIGHUP qutebrowser
sleep 1
notify-send "Reloaded theme"
