#!/usr/bin/env bash
[[ -e $HOME/.config/qutebrowser/greasemonkey/ddg-bg.js ]] || ln -s $HOME/.cache/wal/ddg-bg.js $HOME/.config/qutebrowser/greasemonkey/ && notify-send "Symlinked qutebrowser script."
makoctl reload
hyprctl hyprpaper reload
pkill -SIGHUP qutebrowser
sleep 1
notify-send "Reloaded theme"
