[bar.default]
center = []
end = [ "group:g1" ]
margin_ends = 50
start = [ "control-center", "clock", "notifications", "spacer_2", "media" ]

    [bar.default.dead_zone.actions]
    middle = "settings-open"
    scroll_down = "workspace-switch next"
    scroll_up = "workspace-switch prev"

    [bar.default.monitor.HDMI-A-1]
    background_opacity = 0.0
    center = [ "group:g1" ]
    end = [ "group:g2" ]
    margin_ends = 0
    position = "top"
    shadow = false
    start = [ "group:g3", "spacer_2", "media" ]

        [[bar.default.monitor.HDMI-A-1.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "clock", "notifications" ]
        opacity = 1.0
        padding = 6.0

        [[bar.default.monitor.HDMI-A-1.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "tray", "network", "bluetooth", "volume", "battery" ]
        opacity = 1.0
        padding = 6.0

        [[bar.default.monitor.HDMI-A-1.capsule_group]]
        accordion = true
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g3"
        members = [ "control-center", "settings", "session" ]
        opacity = 0.0
        padding = 6.0

    [bar.default.monitor.eDP-1]
    position = "right"
    center = [ "workspaces" ]
    margin_ends = 280
    reserve_space = false
    smart_auto_hide = false
    start = [ "clock", "notifications", "spacer_2", "media" ]
    thickness = 29

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "tray", "network", "bluetooth", "volume", "battery" ]
    opacity = 1.0
    padding = 6.0

[battery]
warning_threshold = 30

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002", "desktop-widget-0000000000000003" ]

    [desktop_widgets.grid]
    cell_size = 64
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 768.0
    cy = 208.0
    output = "HDMI-A-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        center_text = true
        clock_style = "digital"
        font_family = ""

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 148.0
    cy = 112.0
    output = "eDP-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        clock_style = "digital"
        font_family = "MesloLGL Nerd Font Mono"

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 217.0
    cy = 244.0
    output = "eDP-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        background = false
        hide_when_no_media = false
        layout = "horizontal"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
address = "Podhorie, Slovakia"

[lockscreen]
blur_intensity = 0.79999998211860657
blurred_desktop = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@eDP-1",
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 768.0
    cy = 741.0
    output = "HDMI-A-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 768.0
    cy = 741.0
    output = "eDP-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 768.0
    cy = 432.0
    output = "HDMI-A-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "clock"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 768.0
    cy = 164.5
    output = "eDP-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "clock"

[nightlight]
enabled = true
temperature_night = 3000

[osd]
position = "top_right"
position_vertical = "center_right"

    [osd.kinds]
    lock_keys = false
    media = false

[plugin_settings."aristides/udiskie"]
auto_open_filemanager = true

[plugins]
enabled = [ "aristides/udiskie" ]

[shell]
clipboard_confirm_clear_history = false
polkit_agent = true
screen_time_enabled = true
telemetry_enabled = true

    [shell.launcher.providers.session]
    prefix = "sess"

    [shell.launcher.providers.wallpaper]
    prefix = ""

    [shell.panel]
    control_center_placement = "floating"
    open_near_click_control_center = true
    session_placement = "floating"
    session_position = "center"

[theme]
builtin = "Ayu"
community_palette = "Kemuri Susu"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "ghostty", "kcolorscheme", "niri", "qt", "starship" ]
    community_ids = [ "neovim", "zathura", "lazygit" ]

[wallpaper]
directory = "/home/eisrntao/Pictures/wallpapers"

    [wallpaper.default]
    path = "/home/eisrntao/Pictures/wallpapers/misc/frieren.png"

    [wallpaper.last]
    path = "/home/eisrntao/Pictures/wallpapers/misc/frieren.png"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/eisrntao/Pictures/wallpapers/misc/frieren.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/eisrntao/Pictures/wallpapers/misc/frieren.png"

    [[wallpaper.favorite]]
    community_palette = "Kemuri Susu"
    palette_source = "community"
    path = "/home/eisrntao/Pictures/wallpapers/rain world/rain_world.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    community_palette = "Kemuri Susu"
    palette_source = "community"
    path = "/home/eisrntao/Pictures/wallpapers/minimal/anime-wolf.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    community_palette = "Oasis Abyss"
    palette_source = "community"
    path = "/home/eisrntao/Pictures/wallpapers/landscape/plane.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    community_palette = "Oasis Abyss"
    palette_source = "community"
    path = "/home/eisrntao/Pictures/wallpapers/minimal/astronaut.png"
    theme_mode = "dark"

[widget.battery]
hide_when_full = true
hide_when_plugged = true

[widget.control-center]
glyph = "grid-dots"

[widget.media]
artist_first = true
hide_when_no_media = true
title_scroll = "on_hover"

[widget.network]
show_label = false

[widget.notifications]
hide_when_no_unread = true

[widget.spacer_2]
type = "spacer"

[widget.volume]
show_label = false

[widget.workspaces]
enabled = true
focused_output_only = true
labels_only_when_occupied = true
pill_scale = 0.45000000000000001
show_labels = false
style = "regular"
