[config]

[templates.sddm-noctalia]
input_path = "/usr/share/sddm/themes/sddm-noctalia/template.conf"
output_path = "/usr/share/sddm/themes/sddm-noctalia/theme.conf"
# post_hook = "myapp --reload-theme"

[templates.niri-tweaks]
input_path = "~/.config/niri/template.kdl"
output_path = "~/.config/niri/tweaks.kdl"

[templates.yt-music]
input_path = "~/.config/YouTube Music/template.css"
output_path = "~/.config/YouTube Music/theme.css"
